server:
  port: 18083
  servlet:
    context-path: /m64

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://a.b.c.d:3306/fund?tinyInt1isBit=false&useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: moma
      password:
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJDuMoNNcVoYuoGKEAHF0Gaqt3rF2YSLiRZSbwBWsI+8mf262AnB2OQ9QFdY7u5f+TtOrZE3qtWHiyqBzrjvahUCAwEAAQ==
      filter:
        config:
          enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: @profileActive@